[package]
name = "qrende"
version = "0.1.0"
authors = ["Stefan Lau <github@stefanlau.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
imageproc = "0.17.0"
dbscan = "0.2.0"
bitvec = "0.9.0"

[dev-dependencies]
rusttype = "0.7"